name: rs_ums_test
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.0.0
  google_sign_in: ^6.2.1
  dio: ^5.9.0
  flutter_html: ^3.0.0-beta.2
  intl: ^0.18.1
  shared_preferences: ^2.2.2
  provider: ^6.1.1

  # New dependencies untuk location tracking
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  permission_handler: ^11.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.1   # tambahkan di dev_dependencies

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/logo-rsums.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - assets/icon/logo-rsums.png
    - assets/icon/logo-google.png