// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALNQzO3LfSn_dTadb16o1_fbOTYDDIGDU',
    appId: '1:996137897685:web:85c0667e0b6d14c9e3dc5c',
    messagingSenderId: '996137897685',
    projectId: 'apprsums',
    authDomain: 'apprsums.firebaseapp.com',
    storageBucket: 'apprsums.firebasestorage.app',
    measurementId: 'G-4ZV6JFTEWT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPv8BWlVbirqzVs-H_yCVAVm_kCqQP-H4',
    appId: '1:996137897685:android:bb2a708be8ec96fce3dc5c',
    messagingSenderId: '996137897685',
    projectId: 'apprsums',
    storageBucket: 'apprsums.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmtOxLvVdWfmSQjg7gDTBp4gZILDsfjHY',
    appId: '1:996137897685:ios:58be052eac4e1c0fe3dc5c',
    messagingSenderId: '996137897685',
    projectId: 'apprsums',
    storageBucket: 'apprsums.firebasestorage.app',
    iosBundleId: 'com.example.rsUmsTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmtOxLvVdWfmSQjg7gDTBp4gZILDsfjHY',
    appId: '1:996137897685:ios:58be052eac4e1c0fe3dc5c',
    messagingSenderId: '996137897685',
    projectId: 'apprsums',
    storageBucket: 'apprsums.firebasestorage.app',
    iosBundleId: 'com.example.rsUmsTest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyALNQzO3LfSn_dTadb16o1_fbOTYDDIGDU',
    appId: '1:996137897685:web:d24269677106a763e3dc5c',
    messagingSenderId: '996137897685',
    projectId: 'apprsums',
    authDomain: 'apprsums.firebaseapp.com',
    storageBucket: 'apprsums.firebasestorage.app',
    measurementId: 'G-QGRNWM1ZHH',
  );
}
